
[font]
normal = { family = "Caskaydia Cove Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 10

[window]
dynamic_padding = false
opacity = 0.9
blur = true

[colors]
transparent_background_colors = false

[scrolling]
history = 50000

[general]
# https://alacritty.org/config-alacritty.html

import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
