import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 11

[window]
dynamic_padding = true
opacity = 0.869
blur = false

[colors]
transparent_background_colors = true